Test2-1/Test2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from users.views import RegisterView, LoginView, LogoutView, index,StuInfoPersonalView,EditStuInfo, TeaInfoPersonalView, TeacherLoginView,PaperView,StuExamInfoView,StuGradeInfoView,TeaShowGradeView,TeaSearchGradeView,AddPaperView,StatisticView,CollectView,StuSearchGradeView

urlpatterns = [
    # 管理员登陆
    path('admin/', admin.site.urls),
    path('logout/admin/', admin.site.urls),
    # path('captcha/', include('captcha.urls')),
    path('', index, name="index"),  # 首页
    path('register', RegisterView.as_view(), name="register"),  # 学生注册
    path('login/', LoginView.as_view(), name='login'),  # 学生登录
    # path('logout/', LogoutView.as_view(), name="logout"),
    path('teacherlogin/', TeacherLoginView.as_view(), name='teacherlogin'),  # 老师登录
    path('logout/', LogoutView.as_view(), name='logout'),  # 学生退出
    path('login/personal/', StuInfoPersonalView.StuInfoPersonal, name="StuInfoPersonal"),  # 学生的个人信息
    path('login/personal/editinfo',EditStuInfo.ShowEditInfo,name="ShowEditInfo"), 
    path('login/personal/edit',EditStuInfo.Edit,name="Edit"), 
    path('login/StuExamInfo/', StuExamInfoView.StuExamInfo, name="StuExamInfo"),  # 学生的考试信息
    path('login/StuGradeInfo/', StuGradeInfoView.StuGradeInfo, name="StuGradeInfo"),  # 学生的成绩信息
    path('login/StuCollect/', CollectView.ShowCollect, name="ShowCollect"),  # 收藏夹
    path('login/StuCollect/collectlist/', CollectView.CollectList, name="CollectList"),  # 查看收藏夹
    path('login/deletecollect/', CollectView.DeleteCollect, name="DeleteCollect"),  # 学生取消收藏夹
    path('teacherlogin/personal/', TeaInfoPersonalView.TeaInfoPersonal, name="TeaInfoPersonal"),  # 教师的个人信息
    path('teacherlogin/showgrade/', TeaShowGradeView.TeaShowGrade, name="TeaShowGrade"),  # 教师查看成绩
    path('teacherlogin/statistic/', StatisticView.TeaStatistic, name="TeaStatistic"),  # 教师统计成绩
    path('teacherlogin/statistic/show', StatisticView.ShowSta, name="show"),  # 统计成绩
    path('teacherlogin/addpaper/', AddPaperView.AddPaper, name="AddPaper"),  # 教师组卷
    path('teacherlogin/addpaper/ChooseQuestion/', AddPaperView.ChooseQuestion, name="ChooseQuestion"),
    path('teacherlogin/showgrade/search/', TeaSearchGradeView.TeaSearchGrade, name="TeaSearchGrade"), 
    path('login/StuGradeInfo/search/', StuSearchGradeView.StuSearchGrade, name="StuSearchGrade"),
    path('login/StuExamInfo/StartExam', PaperView.StartExam, name="StartExam"),  # 学生开始考试
    path('login/StuExamInfo/collect/', CollectView.AddCollect, name="AddCollect"),  # 学生添加收藏夹
    url('^calGrade/$',PaperView.calGrade),
    url('^getChoose/$',AddPaperView.GetChoose),
]



Test2-1/users/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser

# Create your models here.

DEPT = (
    ('计算机科学与技术学院', '计算机科学与技术学院'),
    ('电气与自动化学院', '电气与自动化学院'),
    ('外国语学院', '外国语学院'),
    ('理学院', '理学院'),
)

#学院表
class Sdept(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"学院名",choices=DEPT, null=True)
    decs = models.CharField(max_length=500, verbose_name=u"学院说明", default="",null=True)

    class Meta:
        db_table = 'sdept'
        verbose_name = u'学院'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

#班级表
class Sclass(models.Model):
    cid = models.CharField('班号', max_length=20)  # 班号
    sdept = models.ForeignKey(Sdept, verbose_name=u"学院", on_delete=models.CASCADE, null=True)  # 学院

    class Meta:
        db_table = 'sclass'
        verbose_name = u'班级'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.cid


class Student(models.Model):  # 继承，学生表在继承的基础上包含以下内容
    sid = models.CharField('学号', max_length=20, primary_key=True)  # 学号
    password = models.CharField('密码', max_length=40, default='123456')  # 密码
    name = models.CharField('姓名', max_length=20)  # 姓名
    sclass = models.ForeignKey(Sclass, verbose_name=u"班号", on_delete=models.CASCADE, null=True)  # 班号
    sdept = models.ForeignKey(Sdept, verbose_name=u"学院", on_delete=models.CASCADE, null=True)  # 学院
    email = models.EmailField('邮箱', default=None)  # 邮箱
    
    class Meta:  # 表名
        db_table = 'student'
        verbose_name = '学生'
        verbose_name_plural = verbose_name

    def __str__(self):  # 主键
        return self.sid


class Teacher(models.Model):
    sid = models.CharField("教工号", max_length=20, primary_key=True)
    name = models.CharField('姓名', max_length=20)
    sdept = models.ForeignKey(Sdept, verbose_name=u"学院", on_delete=models.CASCADE)  # 学院
    email = models.EmailField('邮箱', default=None)
    password = models.CharField('密码', max_length=40, default='000000')

    class Meta:
        db_table = 'teacher'
        verbose_name = '教师'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sid

#科目表
class Course(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"科目名")
    decs = models.CharField(max_length=500, verbose_name=u"科目说明", default="",null=True)

    class Meta:
        db_table = 'course'
        verbose_name = u'科目'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

#题目标
class Question(models.Model):
    LEVEL = {
        ('1', 'easy'),
        ('2', 'general'),
        ('3', 'difficult'),
    }

    id = models.AutoField(primary_key=True)
    questionType = models.CharField(max_length=20, choices=(("single_choice", u"单选"), ("judgment", u"判断"), ("multiple_choice", u"多选")),default="single_choice", verbose_name=u"题型")
    course = models.ForeignKey(Course, verbose_name=u"科目", on_delete=models.CASCADE)
    content = models.TextField(verbose_name=u"题目内容")
    answer = models.TextField(verbose_name=u"正确答案")
    choice_a = models.TextField(verbose_name=u"A选项", default="A.",null=True)
    choice_b = models.TextField(verbose_name=u"B选项", default="B.",null=True)
    choice_c = models.TextField(verbose_name=u"C选项", default="C.",null=True)
    choice_d = models.TextField(verbose_name=u"D选项", default="D.",null=True)
    choice_e = models.TextField(verbose_name=u"E选项", default="E.",null=True)
    choice_f = models.TextField(verbose_name=u"F选项", default="F.",null=True)
    boolt = models.TextField(verbose_name=u"判断正确", default="对",null=True)
    boolf = models.TextField(verbose_name=u"判断错误", default="错",null=True)
    choice_num = models.IntegerField(verbose_name=u"选项数", default=4)
    level = models.CharField(verbose_name=u'等级', max_length=10, choices=LEVEL,null=True)
    score = models.IntegerField(verbose_name=u'分数', default=1)
    collect = models.ManyToManyField(Student)

    class Meta:
        db_table = 'question'
        verbose_name = u'题目'
        verbose_name_plural = verbose_name

    def get_content(self):  #获取题干
        return self.content

    def __unicode__(self):
        return u"科目：{0}(题干:{1} | 正确答案:{2} )".format(self.course.name, self.content, self.answer)

#试卷表
class Paper(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"科目", default=1, on_delete=models.CASCADE)
    pid = models.ManyToManyField(Question)  # 多对多
    name = models.CharField(max_length=100, verbose_name=u"试卷名称", default=u"")
    start_time = models.DateField(default=datetime.now, verbose_name=u"开始时间")
    single_choice_num = models.IntegerField(verbose_name=u"单选题数", default=0)
    single_choice_score = models.IntegerField(verbose_name=u"单选分值", default=0)
    judgment = models.IntegerField(verbose_name=u"判断题数", default=0)
    judgment_score = models.IntegerField(verbose_name=u"判断分值", default=0)
    multiple_choice_num = models.IntegerField(verbose_name=u"多选题数", default=0)
    multiple_choice_score = models.IntegerField(verbose_name=u"多选分值", default=0)
    total_num = models.IntegerField(verbose_name=u'总题数', default=0)
    total_score = models.IntegerField(verbose_name=u'总分', default=100)
    exam_time = models.IntegerField(verbose_name=u'考试时间（min）', default=120)

    class Meta:
        db_table='paper'
        verbose_name=u'试卷'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return u"{0} ({1}，{2})".format(self.name,self.total_score,self.exam_time)

#成绩表
class Grade(models.Model):
    stu=models.ForeignKey(Student,verbose_name=u"学生",on_delete=models.CASCADE,default='')#添加外键
    exam_name=models.CharField(u'试卷名称',max_length=100,default='')
    grade=models.IntegerField(verbose_name=u'考试成绩', default=0)
    exam_time = models.DateTimeField(default=datetime.now, verbose_name=u"考试时间")
    course = models.ForeignKey(Course, verbose_name=u"科目", default=1, on_delete=models.CASCADE, null=True)
    flag=models.IntegerField(verbose_name=u'成绩类型', default=0)

    class Meta:
        db_table='grade'
        verbose_name=u'成绩'
        verbose_name_plural=verbose_name

    def __unicode__(self):
        return u"({0},{1},{2})".format(self.stu,self.exam_name,self.grade)





Test2-1/templates/addpaper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="/static/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>

    <link rel="stylesheet" href="/static/css/studentinfo.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">


    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    
    <title>组卷</title>
</head>
<body>
    <!--
    <input type="checkbox" id="check">
    <label for="check">
        <i class="fa fa-bars" aria-hidden="true" id="btn"></i>
        <i class="fa fa-times-circle-o" aria-hidden="true" id="cancel"></i>
    </label>
    -->
    <div class="sidebar">
        <header>TestOnline</header>
        <div class="info-photo">
                <div class="profile-dtl">
					<img src="/static/img/10.jpg">
					<h2>{{ request.session.name }}</h2>   <!--此处之后改为用户名字-->
                </div>
            </div>
        <ul>
            <li><a href="{% url 'TeaInfoPersonal' %}">个人信息</a></li>
            <li><a href="{% url 'TeaStatistic' %}">成绩统计</a></li>
            <li><a href="{% url 'TeaShowGrade' %}">成绩查看</a></li>
            <li><a href="{% url 'AddPaper' %}">组卷</a></li>
            <li><a href="{% url 'logout' %}">退出</a></li>
        </ul>
    </div>
    <section>
    <div class="container">
        <div class="tab-content">
            <div id="home" class="container tab-pane active"><br>
                <h3>课程</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>科目</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in course%}
                        <tr class="examinfo">
                            <td>{{ i.name }}</td>
                            <td>
                                <a href="{%url 'ChooseQuestion'%}?sid={{ request.session.sid }}&courseid={{ i.id }}&coursename={{ i.name }}">
                                    <button class="btn btn-primary" id="toExam+{{ i.name }}">开始组卷</button>
                                    <!--<button id="toExam+{{ paper1.name }}">开始考试</button>-->
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </section>
</body>
</html>

Test2-1/templates/adminlogin.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>管理员登录</title>
    <link rel="stylesheet" href="../static/css/login.css">
    <link rel="stylesheet" href="../static/font-awesome-4.7.0/css/font-awesome.css">
</head>
<body>
    <div>
        <i class="fa fa-university fa-2x" aria-hidden="true">
            <a href="{% url 'index' %}">回到首页</a>
        </i>
    </div>
    <form class="box" action="{% url 'login' %}" method="POST" autocomplete="off">  <!--之后页面改成学生登录成功后的页面-->
        {% csrf_token %}
        <h1>管理员登陆</h1>
        <input type="text" id="id_sid" name="sid" placeholder="学号">
        <input type="password" id="id_password" name="password" placeholder="密码">
        <input type="submit" name="" value="登录">
        <a href="{% url 'register' %}">还没有账号？前去注册</a>
        {% csrf_token %}
    </form>
</body>
</html>

Test2-1/templates/choose.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>组卷</title>
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="/static/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/test.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
<style>
.hasBeenAnswer {
	background: #5d9cec;
	color:#fff;
}
</style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
            <li style="position: absolute;left: 70px; font-size: 30px;color: #ffffff">科目:{{ cname }} </li>
    </ul>
</nav>
<div class="main">
    <div class="test_main">
        <div class="test">
            <form name="form1" action="/getChoose/" method="post">
            <input type="hidden" name="cname" value="{{ cname }}">
            <div class="test_title">
                <!--
                <span>共</span><i class="content_lit" id="num"></i><span>题，</span>
                <span>合计</span><i class="content_fs" id="score"></i><span>分</span>-->
                <input type="text" id="pname" name="name" placeholder="试卷名称">
                <input type="text" id="ptime" name="time" placeholder="考试时间">
                <font><input type="submit" name="submitpaper" value="提交"></font>
                <font><input type="reset" name="reset" value="重置"></font>
            </div>
            <div class="test_content">
                <div class="test_content_title">
                    <h2>添加题目</h2>
                </div>
            </div>
            <div class="test_content_nr">
                <ul>
                        {% for i in question %}
                        <li id="{{ i.id }}">
                            <div class="test_content_nr_tt">
                                <input type="radio" class="radioOrCheck" name="{{ i.id }}" value="true"/>
                                <span>({{ i.score }}分)</span>
                                <font>{{ i.content }}</font>
                            </div>

                            <div class="test_content_nr_main">
                                <ul>
                                    <li class="option">
                                        <label>
                                            A.<p class="ue" style="display: inline;">{{ i.choice_a }}</p>
                                        </label>
                                    </li>

                                    <li class="option">
                                        <label>
                                            B.<p class="ue" style="display: inline;">{{ i.choice_b }}</p>
                                        </label>
                                    </li>
                                    {% if i.choice_num == 4 %}
                                    <li class="option">
                                        <label>
                                            C.<p class="ue" style="display: inline;">{{ i.choice_c }}</p>
                                        </label>
                                    </li>

                                    <li class="option">
                                        <label>
                                            D.<p class="ue" style="display: inline;">{{ i.choice_d }}</p>
                                        </label>
                                    </li>
                                    {%endif%}
                                    <span style="color: #085574; font-size:18px; font-weight:bold;">正确答案：{{i.answer}}</span>
                                </ul>
                            </div>
                        </li>
                    {% endfor %}
                    
                </ul>
            </div>
            </form>
        </div>
    </div>

    <div class="foot"></div>
</div>
</body>
</html>

Test2-1/templates/collect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="/static/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>

    <link rel="stylesheet" href="/static/css/studentinfo.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">


    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    
    <title>收藏夹</title>
</head>
<body>
    <!--
    <input type="checkbox" id="check">
    <label for="check">
        <i class="fa fa-bars" aria-hidden="true" id="btn"></i>
        <i class="fa fa-times-circle-o" aria-hidden="true" id="cancel"></i>
    </label>
    -->
    <div class="sidebar">
        <header>TestOnline</header>
        <div class="info-photo">
                <div class="profile-dtl">
					<img src="/static/img/10.jpg">
					<h2>{{ request.session.name }}</h2>   <!--此处之后改为用户名字-->
                </div>
            </div>
        <ul>
            <li><a href="{%url 'StuInfoPersonal' %}">个人信息</a></li>
            <li><a href="{%url 'StuExamInfo' %}">考试信息</a></li>
            <li><a href="{%url 'StuGradeInfo' %}">成绩查看</a></li>
            <li><a href="{%url 'ShowCollect' %}">收藏夹</a></li>
            <li><a href="{% url 'logout' %}">退出</a></li>
        </ul>
    </div>
    <section>
    <div class="container">
        <div class="tab-content">
            <div id="home" class="container tab-pane active"><br>
                <h3>课程</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>科目</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in course%}
                        <tr class="examinfo">
                            <td>{{ i.name }}</td>
                            <td>
                                <a href="{%url 'CollectList'%}?sid={{ request.session.sid }}&courseid={{ i.id }}&coursename={{ i.name }}">
                                    <button class="btn btn-primary" id="toExam+{{ i.name }}">查看收藏夹</button>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </section>
</body>
</html>

Test2-1/templates/editstuinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="/static/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>

    <link rel="stylesheet" href="/static/css/studentinfo.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>个人信息修改</title>
</head>
<body>
    <div class="sidebar">
        <header>TestOnline</header>
        <div class="info-photo">
                <div class="profile-dtl">
                    <img src="/static/img/10.jpg">
                    <h2>{{ request.session.name }}</h2>
                </div>
            </div>
        <ul>
            <li><a href="{%url 'StuInfoPersonal' %}">个人信息</a></li>
            <li><a href="{%url 'StuExamInfo' %}">考试信息</a></li>
            <li><a href="{%url 'StuGradeInfo' %}">成绩查看</a></li>
            <li><a href="{%url 'ShowCollect' %}">收藏夹</a></li>
            <li><a href="{% url 'logout' %}">退出</a></li>
        </ul>
    </div>
    <section>
        <div class="container">
            <div class="tab-content">
                <div id="home" class="container tab-pane active"><br>
                <h3>个人信息</h3>
                <form class="box" action="{% url 'Edit' %}" method="POST" autocomplete="off">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>属性</th>
                                <th>信息</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="examinfo">
                                <td>学号</td>
                                <td>{{ request.session.sid }}</td>
                            </tr>
                            <tr class="examinfo">
                                <td>姓名</td>
                                <td><input type="text" name="name" class="form-control" id="username" placeholder="{{ request.session.name }}" style="text-align: center;font-size: 20px;color: black;"></td>
                            </tr>
                            <tr class="examinfo">
                                <td>学院</td>
                                <td><select name="sdept" class="form-control" id="id_sdept" placeholder="{{ request.session.sdept }}" onchange="document.getElementById('input').value=this.value" style="font-size: 20px;color: black;">
                                    <option value="计算机科学与技术学院">计算机科学与技术学院</option>
                                    <option value="电气与自动化学院">电气与自动化学院</option>
                                    <option value="外国语学院">外国语学院</option>
                                    <option value="理学院">理学院</option>
                                </select></td>
                            </tr>
                            <tr class="examinfo">
                                <td>班号</td>
                                <td><input type="text" id="id_sclass" name="sclass" class="form-control" placeholder="{{ request.session.sclass }}" style="text-align: center;font-size: 20px;color: black;"></td>
                            </tr>
                            <tr class="examinfo">
                                <td>邮箱地址</td>
                                <td><input type="text" id="id_email" name="email" class="form-control" placeholder="{{ request.session.email }}" style="text-align: center;font-size: 20px;color: black;"></td>
                            </tr>    
                        </tbody>    
                    </table>
                    <input type="submit" name="" value="提交更新" style="width: 120px;margin-left: 750px; margin-top: 50px;font-size: 25px;">
                </form>
                    
                
                </div>
            </div>
        </div>
        </section>
</body>
</html>

Test2-1/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>在线做题系统</title>
    <link rel="stylesheet" href="/static/css/index.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">
</head>
<body>
    <!--<div class="services-section">-->
        <div class="inner-width">
            <h1 class="section-title">Test Online</h1>
            <div class="border"></div>
            <div class="services-container">

                <div class="service-box">
                    <div class="service-icon">
                        <i class="fa fa-graduation-cap" aria-hidden="true"></i>    
                    </div>
                    <div style="margin-left:-180px;"><a href="{% url 'login' %}">我是学生</a></div>
                </div>
                
                <div class="service-box">
                    <div class="service-icon">
                        <i class="fa fa-book" aria-hidden="true"></i>
                    </div>
                    <div style="margin-left:-180px;"><a href="{% url 'teacherlogin' %}">我是教师</a></div>
                </div>

                <div class="service-box">
                    <div class="service-icon">
                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                    </div>
                    <div style="margin-left:-180px;"><a href="admin">我是管理员</a></div>
                </div>

            </div>
        </div>
    <!--</div>-->
</body>
</html>

Test2-1/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>学生登录</title>
    <link rel="stylesheet" href="../static/css/login.css">
    <link rel="stylesheet" href="../static/font-awesome-4.7.0/css/font-awesome.css">
</head>
<body>
    <div>
        <i class="fa fa-university fa-2x" aria-hidden="true">
            <a href="{% url 'index' %}">回到首页</a>
        </i>
    </div>
    <form class="box" action="{% url 'login' %}" method="POST" autocomplete="off">  <!--之后页面改成学生登录成功后的页面-->
        {% csrf_token %}
        <h1>学生登录</h1>
        <input type="text" id="id_sid" name="sid" placeholder="学号">
        <input type="password" id="id_password" name="password" placeholder="密码">
        <p class="one">{{msg}}</p>
        <input type="submit" name="" value="登录">
        <a href="{% url 'register' %}">还没有账号？前去注册</a>
    </form>
</body>
</html>

Test2-1/templates/studentinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="/static/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>

    <link rel="stylesheet" href="/static/css/studentinfo.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    
    <title>学生页面</title>
</head>
<body>
    <!--
    <input type="checkbox" id="check">
    <label for="check">
        <i class="fa fa-bars" aria-hidden="true" id="btn"></i>
        <i class="fa fa-times-circle-o" aria-hidden="true" id="cancel"></i>
    </label>
    -->
    <div class="sidebar">
        <header>TestOnline</header>
        <div class="info-photo">
                <div class="profile-dtl">
                    <img src="/static/img/10.jpg">
                    <h2>{{ stu.name }}</h2>
                </div>
        </div>
        <ul>
            <li><a href="{%url 'StuInfoPersonal' %}">个人信息</a></li>
            <li><a href="{%url 'StuExamInfo' %}">考试信息</a></li>
            <li><a href="{%url 'StuGradeInfo' %}">成绩查看</a></li>
            <li><a href="{%url 'ShowCollect' %}">收藏夹</a></li>
            <li><a href="{% url 'logout' %}">退出</a></li>
        </ul>
    </div>
    <section>
    
    </section>
</body>
</html>